### ISSUE TITLE
[RSS] Error in RSS feed

### ISSUE THREAD

**Issue by Leirof** [Gunivers/Gipsy#101]
![image](https://user-images.githubusercontent.com/12165342/196023502-8cd2e8c7-3152-48d9-90a0-3d6350578d47.png)

**Comment by ascpial** [comment]
Je ne suis pas sûr que cette erreur soit liée au RSS, il me semble que c'est un problème lié au traducteur.

Ça ressemble aussi à un bug de la librairie de traduction, donc je ne suis pas sûr que ce soit un problème que l'on puisse régler.

**Comment by ZRunner** [comment]
Si l'erreur vient bien de la lib i18n, elle n'est plus maintenue à jour, j'en ai fait un fork (avec un meilleur typage, quelques fonctionnalités en plus et pas mal de bug fix) ici https://github.com/ZRunner/python-i18n. Par contre j'utilise pas YAML donc je sais pas si c'est cassé ou pas (mais ce sera plus simple de corriger)

**Comment by ascpial** [comment]
Ce problème semble venir des traductions, si il est possible de reproduire ce bug, une nouvelle issue sera créé pour mieux décrire le problème.
