### ISSUE TITLE
[rss] timeout isn't canceled after sending an id in rss embed

### ISSUE THREAD

**Issue by Aeris1One** [Gunivers/Gipsy#197]
![image](https://user-images.githubusercontent.com/29739547/226132393-ec3e295f-71e4-490b-8f8e-aaaa7ddc1ac8.png)

**Comment by ZRunner** [comment]
Nope, le timeout est bien reset parce que l'ID est bien reçu. En revanche, après avoir sélectionné un flux, le bot donne l'état actuel du flux et demande par quelle valeur le modifier (le `use_embed_false` non traduit). Et c'est cette seconde question qui timeout, de manière logique.

Pour le code, voir auours de https://github.com/Gunivers/Gipsy/blob/078c4ff5c0eb8e9b326a0c4d739d7ae7cfb89db8/plugins/rss/rss.py#L867
