### ISSUE TITLE
Mauvaise erreur lors de la vérification du token

### ISSUE THREAD

**Issue by Leirof** [Gunivers/Gipsy#3]
Dans le fichier config.py, le code vérifie uniquement l'option token, sans regarder l'option token_beta qui peut être utilisée si on ne possède qu'une version bêta.
Idéalement il faudrait vérifier l'option au démarrage du bot en fonction du flag utilisé (--beta ou non)

**Comment by ascpial** [comment]
Cette issue n'est plus d'actualité puisque le système de token beta a été retiré.
