### ISSUE TITLE
garder les event du ban qui ne ban pas.

### ISSUE THREAD

**Issue by TretinV3** [Gunivers/Gipsy#55]
Laisser les chances des event qui ne ban pas l’opposant meme si il n’a pas les permissions. Exemple : aeris veux ban tretin mais il n’a pas les perm, comme il n’a pas la permission cela ne va pas ban Tretin. Mais il peut y avoir l’évènement rickroll ou reverse quand meme

**Comment by Aeris1One** [comment]
Ce serait bien que les membres de la guilde, même s'ils n'ont pas la perm de realban puissent fakeban, il serait aussi top de découpler la permission. Peut-être avec un rôle permettant de fakeban inscrit dans la config (par exemple, la Guilde sur Gunivers)

**Comment by ascpial** [comment]
En fait vous cherchez juste à avoir un argument supplémentaire dans les discussions
Soit on demande aux personnes qui ont les permissions de ban si ils sont d'accord, soit on fait un coup d'état et on donne la perm sneaky aux membres de la guilde.
Au choix...

**Comment by TretinV3** [comment]
Non ça permet d’avoir des petites conséquences quand ont fait la commande. Donc si la personne n’a pas la perm elle n’a que les malus (reverse) mais pas les bonus (ban l’autre)

**Comment by ascpial** [comment]
Du coups ça n'a aucun intérêt x)
Le but de la commande de ban est de montrer la supériorité de tes arguments face à la personne en face.
Si tu ne peux que avoir les malus, ça montre juste que tu es inférieur.

**Comment by Aeris1One** [comment]
C'est le cas : ils sont inférieurs

**Comment by ascpial** [comment]
Laissez moi quelques heures, et j'implémente ça dans #48.

**Comment by ascpial** [comment]
La PR #48 a été merge et elle résout certains des problèmes cités ici.
