### ISSUE TITLE
Perms command doesn't work properly

### ISSUE THREAD

**Issue by Leirof** [Gunivers/Gipsy#92]
![image](https://user-images.githubusercontent.com/12165342/183156238-4253e014-fba0-4979-986c-6d758f807ec6.png)

![image](https://user-images.githubusercontent.com/12165342/183156313-e61d5cb7-c8c2-4ff8-94d3-4e65e70f569f.png)

**Comment by ascpial** [comment]
J'ai déplacé cette issue car la commande `!perms` est encore située dans le cœur.
