### ISSUE TITLE
[ban] Get permanent invite link to avoid recreating one for every ban

### ISSUE THREAD

**Issue by Leirof** [Gunivers/Gipsy#98]
Ban command (funny version) create invite link at each execution, which lead to a rate limit. The bot should instead create a permanent invite link and re-use it

**Comment by ascpial** [comment]
Le problème de rate limit n'était pas liée au plugin de ban mais était liée au plugin inviteTracker qui récupérait chaque invitation quand un utilsiateur rejoignait le serveur.
Ce problème est en court dans #117.
